// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TestWeb {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox textBoxEmail;
		
		protected System.Web.UI.WebControls.TextBox textBoxCardHolderName;
		
		protected System.Web.UI.WebControls.TextBox textBoxCardNumber;
		
		protected System.Web.UI.WebControls.TextBox textBoxExpiryMonth;
		
		protected System.Web.UI.WebControls.TextBox textBoxExpiryYear;
		
		protected System.Web.UI.WebControls.TextBox textBoxCVV;
		
		protected System.Web.UI.WebControls.DropDownList ddlInstallmentCount;
		
		protected System.Web.UI.WebControls.Button button1;
		
		protected System.Web.UI.WebControls.Literal ltrOutput;
	}
}
